### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by drobnikj** [nguyeda1/startupjobs2jazzHR#1]
The code looks overall very good, readable, with comments. I think it is not common to have public actor code looks clean like this 👍 
Just a few notes, which I found:
- const should be at the begging of the file, to better readability https://github.com/nguyeda1/startupjobs2jazzHR/blob/main/src/utils.js#L26 (same for ERROR_TYPES const) 
- You can even get just open position from API with /jobs/status/open https://github.com/nguyeda1/startupjobs2jazzHR/blob/main/src/worker.js#L31
- You can use sleep helper from sdk https://sdk.apify.com/docs/api/utils#utilssleepmillis -> https://github.com/nguyeda1/startupjobs2jazzHR/blob/main/src/worker.js#L144
- Maybe use some specific name for the state store of the actor. 'state' is quite generic and can have some collision with other actors https://github.com/nguyeda1/startupjobs2jazzHR/blob/main/main.js#L15
- You ignore all errors coming from actor https://github.com/nguyeda1/startupjobs2jazzHR/blob/main/main.js#L48 and you just log them, it is not a good approach. The actor should end up in a failed state if an unexpected issue happens.
- For logging you can use apify logger https://sdk.apify.com/docs/api/log, you can set debug logs, but it is optional

**Comment by monkey-denky** [comment]
> The code looks overall very good, readable, with comments. I think it is not common to have public actor code looks clean like this 👍
> Just a few notes, which I found:
> 
> * const should be at the begging of the file, to better readability https://github.com/nguyeda1/startupjobs2jazzHR/blob/main/src/utils.js#L26 (same for ERROR_TYPES const)
> * You can even get just open position from API with /jobs/status/open https://github.com/nguyeda1/startupjobs2jazzHR/blob/main/src/worker.js#L31
> * You can use sleep helper from sdk https://sdk.apify.com/docs/api/utils#utilssleepmillis -> https://github.com/nguyeda1/startupjobs2jazzHR/blob/main/src/worker.js#L144
> * Maybe use some specific name for the state store of the actor. 'state' is quite generic and can have some collision with other actors https://github.com/nguyeda1/startupjobs2jazzHR/blob/main/main.js#L15
> * You ignore all errors coming from actor https://github.com/nguyeda1/startupjobs2jazzHR/blob/main/main.js#L48 and you just log them, it is not a good approach. The actor should end up in a failed state if an unexpected issue happens.
> * For logging you can use apify logger https://sdk.apify.com/docs/api/log, you can set debug logs, but it is optional

@drobnikj Thx! I addressed the comments in https://github.com/nguyeda1/startupjobs2jazzHR/pull/2
